[package]
name = "jsony_macros"
version = "0.0.1"
edition = "2021"
authors = ["Thomas Dagenais <exrok@i64.dev>"]
license = "MIT"
readme = "README.md"
description = "proc-macro crate for jsony"

[dependencies]

[lib]
proc-macro = true
