[action.build-jsony-macros]
pwd = "./crates/macro_preprocessor/"
cmd = ["cargo", "run", "../jsony_macros_source", "../jsony_macros"]
cache.key = [
    { modified = "./crates/macro_preprocessor/" },
    { modified = "./crates/jsony_macros_source/" },
]

[test.jsony-unit-tests]
pwd = "."
cmd = ["cargo", "test", "-p", "jsony"]
require = ["build-jsony-macros"]

[test.typos]
cmd = ["typos"]

[action.jsony-tester]
pwd = "./local/tester"
cmd = ["cargo", "run"]
require = ["build-jsony-macros"]

[action.macro-tester]
pwd = "./crates/jsony_macros_source"
cmd = ["cargo", "run"]
